export const CATALOG_RAW = [
  { name: "Vay nhanh Xe máy 18 tháng", variant: "VAR-101", family: "Cầm cố", limit: "3tr – 50tr", rate: "1,5%/tháng", status: "published", channels: ["App", "Web", "PGD"] },
  { name: "Vay ô tô hạn mức", variant: "VAR-102", family: "Hạn mức", limit: "50tr – 2 tỷ", rate: "1,1%/tháng", status: "published", channels: ["App", "PGD"] },
  { name: "Vay xe máy KH thân thiết", variant: "VAR-103", family: "Cầm cố", limit: "3tr – 80tr", rate: "1,0%/tháng", status: "published", channels: ["App", "Web"] },
  { name: "Vay Bullet vàng 3 tháng", variant: "VAR-104", family: "Cầm cố", limit: "5tr – 500tr", rate: "1,3%/tháng", status: "approved", channels: ["PGD"] },
  { name: "Vay tín chấp lương GV", variant: "VAR-105", family: "Tín chấp", limit: "10tr – 100tr", rate: "1,6%/tháng", status: "review", channels: ["App"] },
  { name: "Vay cầm cố DN nhỏ", variant: "VAR-107", family: "Cầm cố", limit: "100tr – 2 tỷ", rate: "1,2%/tháng", status: "draft", channels: ["PGD", "Web"] },
];

export const RELEASE_STEPS_RAW = [
  {
    title: "Xác định Business Intent",
    role: "Product Owner",
    icon: "target",
    desc: "Khởi nguồn từ định hướng kinh doanh: xác định mục tiêu, tệp khách hàng và Financial Obligation Archetype phù hợp.",
    goLabel: "Mở trình tạo Business Intent",
    view: "businessintent",
    input: "Định hướng kinh doanh",
    output: "Business Intent",
    checklist: ["Xác định mục tiêu & KPI kinh doanh", "Chọn Financial Obligation Archetype", "Khoanh vùng tệp khách hàng mục tiêu"],
    tip: "1 Business Intent có thể dẫn xuất nhiều Product Intent.",
  },
  {
    title: "Tạo Product Intent",
    role: "Product Designer",
    icon: "route",
    desc: "Cụ thể hóa ý định sản phẩm: gắn Obligation Nature (is_identify) và bản chất nghĩa vụ tài chính.",
    goLabel: "Mở trình tạo Product Intent",
    view: "intent",
    input: "Business Intent",
    output: "Product Intent",
    checklist: ["Gán Obligation Nature định danh", "Khai báo Obligation Element nền", "Đối chiếu Ma trận FOA × Element"],
    tip: "Ma trận ràng buộc sẽ suy diễn Family hợp lệ cho Intent.",
  },
  {
    title: "Dựng Product Pattern",
    role: "Product Designer",
    icon: "git-branch",
    desc: "Vẽ khuôn sản phẩm: kéo-thả Block vào cấu trúc và gán Obligation Type cho khuôn.",
    goLabel: "Mở Trình dựng Pattern",
    view: "builder", // we will intercept entity='pattern'
    input: "Product Intent",
    output: "Product Pattern",
    checklist: ["Gán Obligation Type cho khuôn", "Kéo-thả Block bắt buộc/tùy chọn", "Khai báo Answer Slot cho từng Block"],
    tip: "Đối chiếu Ma trận Obligation Type × Block để không thiếu Block.",
  },
  {
    title: "Tạo Product Template",
    role: "Product Designer",
    icon: "layout-template",
    desc: "Cụ thể hóa Pattern cho một đối tượng khách hàng (cá nhân/doanh nghiệp) và bối cảnh bán.",
    goLabel: "Mở trình tạo Template",
    view: "template",
    input: "Product Pattern",
    output: "Product Template",
    checklist: ["Chọn đối tượng khách hàng", "Khóa các Block không áp dụng", "Đặt giá trị khung cho Answer Slot"],
    tip: "Template thừa kế cấu trúc Block từ Pattern nguồn.",
  },
  {
    title: "Cấu hình Product Config",
    role: "Product Designer",
    icon: "file-cog",
    desc: "Điền giá trị cho Answer Slot, tạo Config Fragment có thể giới hạn theo Selector Scope.",
    goLabel: "Mở cấu hình Config",
    view: "configForm",
    input: "Product Template",
    output: "Product Config",
    checklist: ["Điền đầy đủ Answer Slot bắt buộc", "Tạo Fragment theo People/Place/Time", "Kiểm tra ràng buộc Attribute"],
    tip: "Mỗi Fragment gán 1 giá trị, có thể chồng theo Selector Scope.",
  },
  {
    title: "Mô phỏng & Kiểm thử",
    role: "Product Designer / QA",
    icon: "zap",
    desc: "Chạy Simulation Engine: dựng lịch trả nợ, dòng tiền và kiểm tra toàn bộ ràng buộc trước khi trình duyệt.",
    goLabel: "Mở Simulation Engine",
    view: "simulation",
    input: "Product Config",
    output: "Kết quả mô phỏng hợp lệ",
    checklist: ["Chạy ≥ 1 kịch bản đại diện", "Đối chiếu ràng buộc (LTV, trần lãi, hạn mức)", "So sánh phương án & xuất báo cáo"],
    tip: "Verdict \"Hợp lệ\" là điều kiện cần để gửi duyệt.",
  },
  {
    title: "Phê duyệt (Maker–Checker)",
    role: "Checker / Approver",
    icon: "circle-dollar-sign",
    desc: "Trình duyệt theo vòng đời Config: Checker rà soát, phê duyệt hoặc trả lại kèm ý kiến.",
    goLabel: "Mở hàng đợi duyệt",
    view: "config",
    input: "Product Config (chờ duyệt)",
    output: "Config đã duyệt",
    checklist: ["Maker gửi duyệt (Draft → Review)", "Checker rà soát & đối chiếu chính sách", "Phê duyệt (Review → Approved)"],
    tip: "Maker không được tự duyệt config của mình.",
  },
  {
    title: "Đóng gói & Phát hành Catalog",
    role: "Vận hành (Operations)",
    icon: "rocket",
    desc: "Đóng gói Product Variant từ Config đã duyệt, chọn kênh phân phối và xuất bản lên Catalog.",
    goLabel: "Mở Product Catalog",
    view: "catalog",
    input: "Config đã duyệt",
    output: "Product Variant trên kệ",
    checklist: ["Đóng gói Variant & gán giá hiển thị", "Chọn kênh (App / Web / PGD)", "Xuất bản (Approved → Published)"],
    tip: "Sau phát hành, Variant đi theo vòng đời sản phẩm.",
  },
];
