import type { BusinessIntent, Pattern, ProductIntent, Template } from "./types";

export const mockBusinessIntents: BusinessIntent[] = [
  {
    id: "BI-001",
    name: "Mở rộng tín dụng cầm cố 2025",
    owner: "Product",
    period: "2025",
    objective: "Tăng thị phần tín dụng cầm cố tại khu vực phía Nam",
    kpis: [
      { metric: "Disbursement", target: "1200", unit: "tỷ VND/năm" },
      { metric: "Customer", target: "50000", unit: "khách/năm" },
    ],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "5000000", ageRange: [20, 55], groups: ["Worker"], regions: ["HCM", "Bình Dương"] },
    status: "approved",
  },
  {
    id: "BI-002",
    name: "Sản phẩm vay xe máy linh hoạt",
    owner: "Product",
    period: "2025",
    objective: "Phát triển sản phẩm vay xe máy cho phân khúc thu nhập thấp",
    kpis: [
      { metric: "Disbursement", target: "800", unit: "tỷ VND/năm" },
      { metric: "NPL", target: "2.5", unit: "%" },
    ],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "4000000", ageRange: [22, 50], groups: ["Worker", "Freelancer"], regions: ["HCM", "Hà Nội"] },
    status: "draft",
  },
  {
    id: "BI-003",
    name: "Tín dụng tiêu dùng digital-first",
    owner: "Digital",
    period: "2025",
    objective: "Tạo luồng vay online hoàn toàn qua app",
    kpis: [
      { metric: "Disbursement", target: "500", unit: "tỷ VND/năm" },
      { metric: "TAT", target: "15", unit: "phút" },
    ],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "8000000", ageRange: [25, 45], groups: ["Office"], regions: ["HCM", "Hà Nội", "Đà Nẵng"] },
    status: "review",
  },
  {
    id: "BI-004",
    name: "Cho vay cầm cố đồ gia dụng",
    owner: "Product",
    period: "2026",
    objective: "Mở rộng danh mục tài sản cầm cố sang đồ gia dụng",
    kpis: [{ metric: "Disbursement", target: "300", unit: "tỷ VND/năm" }],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "3000000", ageRange: [20, 60], groups: ["Worker", "Retired"], regions: ["Toàn quốc"] },
    status: "draft",
  },
  {
    id: "BI-005",
    name: "Vay tín chấp lương nhân viên",
    owner: "Product",
    period: "2025",
    objective: "Sản phẩm vay tín chấp dựa trên lịch sử lương",
    kpis: [
      { metric: "Disbursement", target: "600", unit: "tỷ VND/năm" },
      { metric: "Approval Rate", target: "65", unit: "%" },
    ],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "7000000", ageRange: [25, 50], groups: ["Office"], regions: ["HCM", "Hà Nội"] },
    status: "published",
  },
  {
    id: "BI-006",
    name: "Mở rộng vay xe ô tô cũ",
    owner: "Product",
    period: "2025",
    objective: "Phát triển sản phẩm vay ô tô đã qua sử dụng",
    kpis: [{ metric: "Disbursement", target: "400", unit: "tỷ VND/năm" }],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "15000000", ageRange: [28, 55], groups: ["Office", "Business"], regions: ["HCM"] },
    status: "draft",
  },
  {
    id: "BI-007",
    name: "Loyalty lending program",
    owner: "Digital",
    period: "2026",
    objective: "Ưu đãi lãi suất cho khách hàng trung thành",
    kpis: [
      { metric: "Retention", target: "80", unit: "%" },
      { metric: "Cross-sell", target: "30", unit: "%" },
    ],
    archetype: "FOA_TERM_LOAN",
    segment: { income: "5000000", ageRange: [20, 55], groups: ["Existing"], regions: ["Toàn quốc"] },
    status: "draft",
  },
];

export const mockProductIntents: ProductIntent[] = [
  {
    id: "PI-001",
    businessIntentId: "BI-001",
    name: "Vay cầm cố linh hoạt",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE"],
    status: "approved",
  },
  {
    id: "PI-002",
    businessIntentId: "BI-001",
    name: "Vay cầm cố trả góp cố định",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE", "PAYMENT_MULTISTEP_INSTALLMENT"],
    status: "draft",
  },
  {
    id: "PI-003",
    businessIntentId: "BI-002",
    name: "Vay xe máy tiêu chuẩn",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE"],
    status: "published",
  },
  {
    id: "PI-004",
    businessIntentId: "BI-002",
    name: "Vay xe máy ưu đãi nhân viên",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE", "EVENT_LENDER_DISBURSEMENT"],
    status: "review",
  },
  {
    id: "PI-005",
    businessIntentId: "BI-003",
    name: "Vay online tức thì",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION"],
    status: "draft",
  },
  {
    id: "PI-006",
    businessIntentId: "BI-003",
    name: "Vay digital có tài sản đảm bảo",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE"],
    status: "draft",
  },
  {
    id: "PI-007",
    businessIntentId: "BI-004",
    name: "Cầm cố đồ gia dụng cơ bản",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE"],
    status: "draft",
  },
  {
    id: "PI-008",
    businessIntentId: "BI-005",
    name: "Vay tín chấp lương cơ bản",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION"],
    status: "approved",
  },
  {
    id: "PI-009",
    businessIntentId: "BI-005",
    name: "Vay tín chấp lương premium",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "EVENT_LENDER_DISBURSEMENT"],
    status: "draft",
  },
  {
    id: "PI-010",
    businessIntentId: "BI-006",
    name: "Vay ô tô cũ tiêu chuẩn",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "ASSET_PLEDGE"],
    status: "draft",
  },
  {
    id: "PI-011",
    businessIntentId: "BI-007",
    name: "Vay loyalty trả góp",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION"],
    status: "draft",
  },
  {
    id: "PI-012",
    businessIntentId: "BI-007",
    name: "Vay loyalty hạn mức quay vòng",
    archetype: "FOA_TERM_LOAN",
    elementCodes: ["TERM_LOAN_OBLIGATION", "PRINCIPAL_NO_INCREASE_MULTI_DECREASE"],
    status: "draft",
  },
];

export const mockPatterns: Pattern[] = [
  {
    id: "PAT-001",
    code: "PAT_PLEDGE_INSTALLMENT",
    name: "Pledge Installment Pattern",
    obligationTypeCodes: ["OT_PLEDGE_INSTALLMENT"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_FEE", order: 3, required: false },
      { blockId: "BLK_PENALTY", order: 4, required: false },
    ],
    status: "published",
  },
  {
    id: "PAT-002",
    code: "PAT_PLEDGE_REVOLVING",
    name: "Pledge Revolving Pattern",
    obligationTypeCodes: ["OT_PLEDGE_REVOLVING"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_LIMIT", order: 3, required: true },
    ],
    status: "approved",
  },
  {
    id: "PAT-003",
    code: "PAT_VEHICLE_STANDARD",
    name: "Vehicle Loan Standard",
    obligationTypeCodes: ["OT_PLEDGE_INSTALLMENT"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_INSURANCE", order: 3, required: true },
      { blockId: "BLK_FEE", order: 4, required: false },
    ],
    status: "draft",
  },
  {
    id: "PAT-004",
    code: "PAT_UNSECURED_SALARY",
    name: "Unsecured Salary Loan",
    obligationTypeCodes: ["OT_UNSECURED_INSTALLMENT"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_SCORING", order: 3, required: true },
    ],
    status: "draft",
  },
  {
    id: "PAT-005",
    code: "PAT_DIGITAL_FAST",
    name: "Digital Fast Loan",
    obligationTypeCodes: ["OT_UNSECURED_INSTALLMENT"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_EKYC", order: 3, required: true },
    ],
    status: "review",
  },
  {
    id: "PAT-006",
    code: "PAT_LOYALTY_FLEX",
    name: "Loyalty Flex Pattern",
    obligationTypeCodes: ["OT_PLEDGE_INSTALLMENT", "OT_PLEDGE_REVOLVING"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_LOYALTY", order: 3, required: true },
    ],
    status: "draft",
  },
  {
    id: "PAT-007",
    code: "PAT_HOME_APPLIANCE",
    name: "Home Appliance Pawn",
    obligationTypeCodes: ["OT_PLEDGE_INSTALLMENT"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_APPRAISAL", order: 3, required: true },
    ],
    status: "draft",
  },
  {
    id: "PAT-008",
    code: "PAT_USED_CAR",
    name: "Used Car Loan Pattern",
    obligationTypeCodes: ["OT_PLEDGE_INSTALLMENT"],
    blocks: [
      { blockId: "BLK_INTEREST", order: 1, required: true },
      { blockId: "BLK_PRINCIPAL", order: 2, required: true },
      { blockId: "BLK_INSURANCE", order: 3, required: true },
      { blockId: "BLK_APPRAISAL", order: 4, required: true },
    ],
    status: "draft",
  },
];

export const mockTemplates: Template[] = [
  {
    id: "TPL-001",
    name: "Template cầm cố tiêu chuẩn",
    patternId: "PAT-001",
    audience: "Mass",
    lockedBlockIds: ["BLK_INTEREST"],
    frames: [
      { slotCode: "base_rate", min: "0.3%/tháng", max: "1.65%/tháng", defaultValue: "1.5%/tháng" },
      { slotCode: "max_amount", min: "500,000", max: "100,000,000", defaultValue: "30,000,000" },
    ],
    status: "published",
  },
  {
    id: "TPL-002",
    name: "Template cầm cố doanh nghiệp",
    patternId: "PAT-001",
    audience: "SME",
    lockedBlockIds: ["BLK_INTEREST", "BLK_PRINCIPAL"],
    frames: [
      { slotCode: "base_rate", min: "0.8%/tháng", max: "1.5%/tháng", defaultValue: "1.2%/tháng" },
      { slotCode: "max_amount", min: "10,000,000", max: "500,000,000", defaultValue: "100,000,000" },
    ],
    status: "approved",
  },
  {
    id: "TPL-003",
    name: "Template xe máy phổ thông",
    patternId: "PAT-003",
    audience: "Mass",
    lockedBlockIds: ["BLK_INTEREST"],
    frames: [
      { slotCode: "base_rate", min: "1.0%/tháng", max: "1.8%/tháng", defaultValue: "1.5%/tháng" },
      { slotCode: "max_term", min: "3", max: "24", defaultValue: "12" },
    ],
    status: "published",
  },
  {
    id: "TPL-004",
    name: "Template xe máy ưu đãi",
    patternId: "PAT-003",
    audience: "Loyalty",
    lockedBlockIds: ["BLK_INTEREST", "BLK_FEE"],
    frames: [
      { slotCode: "base_rate", min: "0.8%/tháng", max: "1.2%/tháng", defaultValue: "1.0%/tháng" },
    ],
    status: "draft",
  },
  {
    id: "TPL-005",
    name: "Template vay revolving",
    patternId: "PAT-002",
    audience: "Mass",
    lockedBlockIds: ["BLK_LIMIT"],
    frames: [
      { slotCode: "base_rate", min: "1.2%/tháng", max: "2.0%/tháng", defaultValue: "1.5%/tháng" },
      { slotCode: "credit_limit", min: "5,000,000", max: "50,000,000", defaultValue: "20,000,000" },
    ],
    status: "draft",
  },
  {
    id: "TPL-006",
    name: "Template vay tín chấp lương",
    patternId: "PAT-004",
    audience: "Office Worker",
    lockedBlockIds: ["BLK_SCORING"],
    frames: [
      { slotCode: "base_rate", min: "1.5%/tháng", max: "2.5%/tháng", defaultValue: "2.0%/tháng" },
      { slotCode: "max_amount", min: "5,000,000", max: "80,000,000", defaultValue: "30,000,000" },
    ],
    status: "review",
  },
  {
    id: "TPL-007",
    name: "Template vay online nhanh",
    patternId: "PAT-005",
    audience: "Digital",
    lockedBlockIds: ["BLK_EKYC"],
    frames: [
      { slotCode: "base_rate", min: "1.8%/tháng", max: "3.0%/tháng", defaultValue: "2.5%/tháng" },
      { slotCode: "max_amount", min: "1,000,000", max: "20,000,000", defaultValue: "10,000,000" },
    ],
    status: "draft",
  },
  {
    id: "TPL-008",
    name: "Template cầm cố đồ gia dụng",
    patternId: "PAT-007",
    audience: "Mass",
    lockedBlockIds: [],
    frames: [
      { slotCode: "base_rate", min: "1.5%/tháng", max: "2.5%/tháng", defaultValue: "2.0%/tháng" },
    ],
    status: "draft",
  },
  {
    id: "TPL-009",
    name: "Template vay ô tô cũ",
    patternId: "PAT-008",
    audience: "Mass",
    lockedBlockIds: ["BLK_APPRAISAL"],
    frames: [
      { slotCode: "base_rate", min: "0.8%/tháng", max: "1.5%/tháng", defaultValue: "1.1%/tháng" },
      { slotCode: "max_amount", min: "50,000,000", max: "800,000,000", defaultValue: "300,000,000" },
    ],
    status: "draft",
  },
  {
    id: "TPL-010",
    name: "Template loyalty trả góp",
    patternId: "PAT-006",
    audience: "Loyalty",
    lockedBlockIds: ["BLK_LOYALTY"],
    frames: [
      { slotCode: "base_rate", min: "0.5%/tháng", max: "1.0%/tháng", defaultValue: "0.8%/tháng" },
    ],
    status: "draft",
  },
  {
    id: "TPL-011",
    name: "Template cầm cố cao cấp",
    patternId: "PAT-001",
    audience: "Premium",
    lockedBlockIds: ["BLK_INTEREST", "BLK_PRINCIPAL"],
    frames: [
      { slotCode: "base_rate", min: "0.5%/tháng", max: "1.0%/tháng", defaultValue: "0.8%/tháng" },
      { slotCode: "max_amount", min: "50,000,000", max: "1,000,000,000", defaultValue: "200,000,000" },
    ],
    status: "draft",
  },
  {
    id: "TPL-012",
    name: "Template xe máy trả trước",
    patternId: "PAT-003",
    audience: "Mass",
    lockedBlockIds: [],
    frames: [
      { slotCode: "base_rate", min: "1.2%/tháng", max: "1.8%/tháng", defaultValue: "1.5%/tháng" },
      { slotCode: "down_payment", min: "10%", max: "50%", defaultValue: "20%" },
    ],
    status: "draft",
  },
  {
    id: "TPL-013",
    name: "Template vay nhanh nhân viên",
    patternId: "PAT-004",
    audience: "Employee",
    lockedBlockIds: ["BLK_SCORING"],
    frames: [
      { slotCode: "base_rate", min: "1.0%/tháng", max: "1.8%/tháng", defaultValue: "1.5%/tháng" },
    ],
    status: "approved",
  },
  {
    id: "TPL-014",
    name: "Template revolving loyalty",
    patternId: "PAT-002",
    audience: "Loyalty",
    lockedBlockIds: ["BLK_LIMIT", "BLK_INTEREST"],
    frames: [
      { slotCode: "base_rate", min: "0.8%/tháng", max: "1.5%/tháng", defaultValue: "1.0%/tháng" },
      { slotCode: "credit_limit", min: "10,000,000", max: "100,000,000", defaultValue: "50,000,000" },
    ],
    status: "draft",
  },
  {
    id: "TPL-015",
    name: "Template digital SME",
    patternId: "PAT-005",
    audience: "SME",
    lockedBlockIds: ["BLK_EKYC"],
    frames: [
      { slotCode: "base_rate", min: "1.5%/tháng", max: "2.5%/tháng", defaultValue: "2.0%/tháng" },
      { slotCode: "max_amount", min: "10,000,000", max: "200,000,000", defaultValue: "50,000,000" },
    ],
    status: "draft",
  },
];
