import {
  Blocks,
  FileCog,
  GitBranch,
  LayoutTemplate,
  Library,
  Shapes,
  Tags,
} from "lucide-react";
import type { DashboardOverview } from "./types";

const pipelineCounts = [12, 8, 15, 34, 21, 18];
const pipelineMax = Math.max(...pipelineCounts);

export const dashboardOverview: DashboardOverview = {
  kpis: [
    {
      id: "selling-products",
      label: "Sản phẩm đang bán",
      value: "21",
      delta: "+3",
      tone: "green",
      icon: Shapes,
    },
    {
      id: "patterns",
      label: "Pattern đang dựng",
      value: "8",
      delta: "2 chờ duyệt",
      tone: "gold",
      icon: GitBranch,
    },
    {
      id: "configs-review",
      label: "Config chờ phê duyệt",
      value: "5",
      delta: "maker-checker",
      tone: "review",
      icon: FileCog,
    },
    {
      id: "catalog-items",
      label: "Catalog items",
      value: "18",
      delta: "3 kênh",
      tone: "green",
      icon: Library,
    },
    {
      id: "obligation-types",
      label: "Obligation Types",
      value: "14",
      delta: "4 family",
      tone: "neutral",
      icon: Tags,
    },
  ],
  pipeline: [
    { id: "intent", label: "Intent", count: "12", sub: "định hướng", color: "#9ED9BC", darkText: true },
    { id: "pattern", label: "Pattern", count: "8", sub: "bản vẽ", color: "#5FC596", darkText: true },
    { id: "template", label: "Template", count: "15", sub: "khung", color: "#22A86F", darkText: true },
    { id: "config", label: "Config", count: "34", sub: "tham số", color: "#0E8C5A" },
    { id: "variant", label: "Variant", count: "21", sub: "đóng gói", color: "#E8920C" },
    { id: "catalog", label: "Catalog", count: "18", sub: "trên kệ", color: "#0B7349" },
  ].map((step, index) => ({
    ...step,
    barHeight: Math.round(34 + (pipelineCounts[index] / pipelineMax) * 54),
  })),
  activities: [
    {
      id: "cfg-review",
      actor: "Trần Lan",
      action: "gửi duyệt",
      target: "CFG-0042 Vay nhanh Xe máy",
      time: "3 phút trước",
      channel: "Web",
      tag: "Config",
      tone: "review",
      icon: FileCog,
    },
    {
      id: "tpl-approved",
      actor: "Lê Minh",
      action: "phê duyệt",
      target: "TPL-002 Vay cầm cố DN",
      time: "27 phút trước",
      channel: "Web",
      tag: "Template",
      tone: "info",
      icon: LayoutTemplate,
    },
    {
      id: "pattern-draft",
      actor: "Phạm An",
      action: "tạo mới",
      target: "PT-004 Khuôn vay hạn mức",
      time: "1 giờ trước",
      channel: "Web",
      tag: "Pattern",
      tone: "green",
      icon: GitBranch,
    },
    {
      id: "variant-published",
      actor: "Hệ thống",
      action: "xuất bản",
      target: "VAR-103 Vay xe máy thân thiện",
      time: "hôm qua",
      channel: "API",
      tag: "Variant",
      tone: "green",
      icon: Shapes,
    },
    {
      id: "block-updated",
      actor: "Lê Minh",
      action: "cập nhật",
      target: "Base Rate - BLOCK_INTEREST",
      time: "hôm qua",
      channel: "Web",
      tag: "Block",
      tone: "neutral",
      icon: Blocks,
    },
  ],
  families: [
    { name: "Loan Obligation", count: "10", pct: "48%", color: "#0E8C5A" },
    { name: "Facility", count: "5", pct: "24%", color: "#E8920C" },
    { name: "Conditional", count: "3", pct: "14%", color: "#5FC596" },
    { name: "Unsecured", count: "3", pct: "14%", color: "#9ED9BC" },
  ],
  statusBars: [
    { label: "Đã xuất bản", count: "39", pct: "46%", color: "#0E8C5A" },
    { label: "Đã duyệt", count: "18", pct: "21%", color: "#5FC596" },
    { label: "Đang duyệt", count: "16", pct: "19%", color: "#E8920C" },
    { label: "Bản nháp", count: "12", pct: "14%", color: "#CDD9D2" },
  ],
};
